# Generated by Django 5.0.6 on 2024-07-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('p_age', models.CharField(max_length=100)),
                ('p_date', models.DateTimeField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=100)),
            ],
        ),
    ]
