# Generated by Django 5.0.6 on 2024-07-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerinfo',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registerinfo',
            name='p_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registerinfo',
            name='p_date',
            field=models.CharField(max_length=100),
        ),
    ]
